# Site settings
name: RubyCoach
title: RubyCoach - Aprenda a programar em Ruby
email: robsonmarques@rubycoach.com.br
description: > # this means to ignore newlines until "baseurl:"
  Aprenda de uma vez por todas a programar em Ruby
  com Ruby on Rails e todo o stack de ferramentas
  essenciais para o desenvolvimento web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubycoach.com.br" # the base hostname & protocol for your site
facebook_username: rubycoach
twitter_username: rubycoach
youtube_username: channel/UCEinXIZkk1flS_bLm504_2A
github_username:  rubycoach
timezone: America/Sao_Paulo
permalink: none

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
